# docker-compose.yml
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.3.0
    container_name: anvil
    environment:
        ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
        - "8545:8545"
    entrypoint: anvil
    #command: ["--fork-url", "https://reth-ethereum.ithaca.xyz/rpc", "--fork-block-number", "21500213"]
